schema_version: 1

context:
  version: 2.3.2

package:
  name: caper
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/caper/caper-${{ version }}.tar.gz
  sha256: ef698c9c34fa181759cfa84813ccc07b5ed466931410c1cca36da01808ca363a

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyhocon >=0.3.53
    - requests >=2.20
    - pyopenssl
    - autouri >=0.2.3
    - miniwdl >=0.7.0
    - humanfriendly
    - numpy >=1.8.2
    - pandas >=1.0
    - scikit-learn >=0.19.2
    - matplotlib >=1.5
    - six >=1.13.0

tests:
  - python:
      imports:
        - caper
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  summary: Cromwell Assisted Pipeline ExecutoR
  description: |
    Python wrapper for Cromwell
  homepage: https://github.com/ENCODE-DCC/caper
  repository: https://github.com/ENCODE-DCC/caper

extra:
  recipe-maintainers:
    - danielnachun
    - leepc12
